# Generated by Django 3.1.6 on 2021-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_amount',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
