# Generated by Django 3.1.6 on 2021-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[(1, 'Lite'), (2, 'Premium')], default=1, max_length=1),
        ),
    ]
