# Generated by Django 3.1.6 on 2021-02-23 06:40

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='random_id',
            field=models.CharField(blank=True, default=account.models.generate_profile_id, max_length=20, null=True),
        ),
    ]
