# Generated by Django 3.1.6 on 2021-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210429_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Not Active')], default=1, max_length=1),
        ),
    ]
