# Generated by Django 3.1.6 on 2021-03-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20210223_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isEnded',
            field=models.BooleanField(default=False),
        ),
    ]
