# Generated by Django 3.1.6 on 2021-03-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210223_0840'),
        ('provider', '0003_booking_isended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=10)),
                ('years_of_experience', models.CharField(choices=[('0-2', 'Entry (0-2yrs)'), ('3-5', 'Mid (3-5yrs)'), ('5+', 'Senior (5+ yrs)')], default='0-2', max_length=4)),
                ('registered_council', models.CharField(choices=[('HPCSA', 'Health Professions Council of South Africa'), ('CCSA', 'Council for Counsellors in South Africa')], default='HPCSA', max_length=5)),
                ('electronic_card', models.FileField(blank=True, null=True, upload_to='provider_files')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='account.profile')),
            ],
        ),
    ]
