# Generated by Django 3.1.6 on 2021-04-06 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_today', models.CharField(choices=[('LW', 'Good'), ('MD', 'Okay'), ('HG', 'Not Okay')], default='LW', max_length=2)),
                ('daily_life_feeling', models.CharField(choices=[('J', 'Joyful'), ('C', 'Calm'), ('A', 'Anxious'), ('H', 'Helpless'), ('D', 'Depressed'), ('M', 'Mixed')], default='J', max_length=1)),
                ('focus_area', models.CharField(choices=[('SAX', 'Stress & Anxiety'), ('RTN', 'Relationships'), ('WPF', 'Work Performance'), ('LCH', 'Life Challenges'), ('IBL', 'Inclusion & Belonging')], default='SAX', max_length=3)),
                ('expectation', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_booking', to='provider.booking')),
            ],
        ),
    ]
