# Generated by Django 3.1.6 on 2021-03-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_stripecustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
