# Generated by Django 3.1.6 on 2021-04-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_provider'),
        ('company', '0004_delete_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made_by_company', to='provider.booking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bookings', to='company.company')),
            ],
        ),
    ]
